config/routes.rb
Rails.application.routes.draw do

  root "topics#index"

  resources :topics, only: [ :index, :new, :create, :show ] do
    resources :comments, only: [ :create ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
# == Schema Information
#
# Table name: blacklists
#
#  id         :integer          not null, primary key
#  word       :string
#  regex_word :string
#

class Blacklist < ApplicationRecord

  before_save :create_regex_word


  def self.sanitize!(text)
    self.all.each do |word|
      reg = Regexp.new(word.regex_word, "i")
      stars = "*"*(word.word.length)
      text.gsub!(reg, stars)
    end
    return text
  end

  private

  def create_regex_word
    letters_variation = {
      'a' => "[a@4]",
      'e' => "[e3]",
      'i' => "[i!|]",
      'o' => "[o0]"
    }

    self.regex_word = self.word
    letters_variation.each do |key, value|
      self.regex_word = self.regex_word.gsub(key, value)
    end
  end


end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  comment_id :integer
#  topic_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_comment_id  (comment_id)
#  index_comments_on_topic_id    (topic_id)
#
# Foreign Keys
#
#  fk_rails_6545a5f2bc  (comment_id => comments.id)
#

class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :comment, required: false
  has_many :replies, class_name: "Comment", foreign_key: "comment_id", dependent: :destroy

  validates :body, presence: true

  before_save :sanitize

  private

  def sanitize
    Blacklist.sanitize!(body)
  end

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Topic < ApplicationRecord

  has_many :comments, inverse_of: :topic, dependent: :destroy
  accepts_nested_attributes_for :comments

  validates :title, presence: true
  validates :comments, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.build(comment_params)

    if @comment.save
      redirect_to topic_path(@topic), notice: "Novo comentário."
    else
      redirect_to topic_path(@topic), notice: "Um erro ocorreu."
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:body, :topic_id, :comment_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [ :show ]

  def index
    @topics = Topic.page params[:page]
  end

  def new
    @topic = Topic.new
    @message = @topic.comments.build
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to topics_path, notice: "Novo Tópico Criado"
    else
      render "new"
    end
  end

  def show
    @comment = Comment.new
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, comments_attributes: [ :id, :body, :topic_id ])
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/_comment_form.html.erb
<%= form_for [@topic, @comment] do |f| %>

  <%= f.text_area :body %>
  <%= f.hidden_field(:comment_id, value: comment_id) %>
  <%= f.submit %>

<% end %>

app/views/topics/_comments.html.erb
<ol>
  <li>
    <i><%= comment.created_at %> - </i>
    <%= comment.body %>
    <button class="btn-reply" data-id=<%= comment.id %>>Reply</button>

    <% comment.replies.each do |reply| %>
        <%= render('comments', comment: reply) %>
    <% end %>

    <div class="comment-reply" id=<%= "comment-reply-#{comment.id}" %>>
      <%= render partial: "comment_form", locals: { comment_id: comment.id } %>
    </div>

  </li>
</ol>

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
<h3><%= pluralize(@topic.errors.count, 'erro', plural: 'erros') %></h3>
<ul>
  <% @topic.errors.full_messages.each do |message| %>
  <li> <%= message %> </li>
  <% end %>
</ul>
<% end %>

<%= form_for @topic do |f| %>

  <h4><%= f.label :title, "Titulo" %></h4>
  <%= f.text_field :title %> <br />

  <%= f.fields_for :comments do |ff| %>
    <h4><%= ff.label :body, "Mensagem" %></h4>
    <%= ff.text_area :body %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Editar Tópico</h1>

<%= render 'form' %>
<%= link_to "Voltar", topics_path(@topic) %>

app/views/topics/index.html.erb
<h1>Tópicos</h1>

<%= link_to "Novo Tópico", new_topic_path %>

<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to "#{topic.created_at} - #{topic.title}", topic_path(topic) %></li>
  <% end %>
  <br/>
  <%= paginate @topics %>
</ul>

app/views/topics/new.html.erb
<h1>Novo Tópico</h1>

<%= render 'form' %>
<%= link_to "Voltar", topics_path %>

app/views/topics/show.html.erb
<%= link_to "[home]", topics_path %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= render partial: 'comments', locals: { comment: @topic.comments.first } %>